---
# Test
- name: Listen for events on a webhook
  hosts: all
  sources:
    - name: Match events posted to port 5000
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
#    - name: Debug if the webhook has a payload
#      condition: event.payload is defined
#      action:
#        debug:
    - name: Print "Ansible is great" if payload message is Message A 
      condition: event.payload.message == "Message A"
      action:
        debug:
          mesg: "Ansible is great"
    - name: Print "Red Hat is great" if payload message is Message B
      condition: event.payload.message == "Message B"
      action:
        debug:
          msg: "Red Hat is great"      
