---
- name: Listen for events on a webhook
  hosts: all
  sources:
    - name: Match events posted to port 5000
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
      filters:
        - ansible.eda.dashes_to_underscores:
  rules:

    - name: Restart web server when payload.message is Restart webserver and payload.server is defined 
      condition: event.payload.message == "Restart webserver" and event.payload.server is defined
      action:
        run_job_template:
          name: "paw_EDA_demo_restart_webserver"
          organization: "Default"
          job_args:
            extra_vars:
              eda_input_webserver: "{{ event.payload.server }}"
