---
- name: Trigger EDA Event
  hosts: localhost
  vars:
    eda_endpoint: "https://hlaio01.idm.lokidev.xyz:443/eda-event-streams/api/eda/v1/external_event_stream/8536e7d2-4424-4775-ae26-8584c2cce6d9/post/"
    eda_message: "Restart webserver"
    eda_server: "hlrhel801.idm.lokidev.xyz"
    eda_auth_username: "edapaw"
    ed_auth_password: "test1234"
  tasks:
    - name: POST Request trigger
      ansible.builtin.uri:
        url: "{{ eda_endpoint }}"
        url_username: "{{ eda_auth_username }}"
        url_password: "{{ eda_auth_password }}"
        validate_certs: false
        method: POST
        force_basic_auth: true
        body_format: json
        body:
          message: "{{ eda_message }}"
          server: "{{ eda_server }}"
        headers:
          Content-Type: application/json
